Repository jsdcommunity/build_Together_Freelacing-site-for-Developers_FrontEnd, pull requests merged in 2021-11, with the labels that each got.

#9 Signup finished
  .prettierrc.json
  package.json
  public/svg/cancel.svg
  public/svg/success-mail.svg
  public/svg/warn-notify.svg
  src/App.js
  src/components/ConfirmAccountContent/ConfirmAccountContent.css
  src/components/ConfirmAccountContent/ConfirmAccountContent.jsx
  src/components/Header/Header.jsx
  src/components/MultiItemInput/MultiItemInput.css
  src/components/MultiItemInput/MultiItemInput.jsx
  src/components/SignUpSteps/Finish.jsx
  src/components/SignUpSteps/SignUpSteps.css
  src/components/SignUpSteps/SignUpSteps.jsx
  src/components/SignUpSteps/Step1.jsx
  src/components/SignUpSteps/Step2.jsx
  src/components/SignUpSteps/Step3.jsx
  src/config/api.js
  src/helpers/api/index.js
  src/helpers/index.js
  src/pages/ConfirmAccount.jsx
  src/pages/SignUp.jsx
  src/redux/actions/darkMode.js
  src/redux/actions/signUpSteps.js
  src/redux/reducers/signUpSteps.js
  src/redux/store.js
  src/utils/constants.js
  yarn.lock
Labels: enhancement, in-progress

#13 Resolved issue #12
  src/components/LoginContent/LoginContent.jsx
Labels: awaiting-review, improvment, ui/ux

#14 Merge `master` into `explore-page`
  src/components/LoginContent/LoginContent.jsx
Labels: improvment

#15 Reset password finished
  src/App.js
  src/components/ResetPasswordContent/ResetPasswordContent.jsx
  src/helpers/api/index.js
  src/pages/ResetPassword.jsx
Labels: enhancement

#11 Explore page
  package.json
  public/svg/empty.svg
  src/App.js
  src/components/ExploreContent/ExploreContent.jsx
  src/components/Header/Header.jsx
  src/components/JobCard/JobCard.jsx
  src/components/JobDetailsModal/JobDetailsModal.jsx
  src/helpers/api/index.js
  src/pages/Explore.jsx
  src/redux/actions/jobs.js
  src/redux/reducers/jobs.js
  src/redux/store.js
  yarn.lock
Labels: enhancement

#16 Homepage content
  package.json
  public/assets/freelancer.png
  public/assets/hero-man.png
  public/assets/testimonial-1.png
  public/svg/android-app.svg
  public/svg/cross-platform.svg
  public/svg/desktop-app.svg
  public/svg/features.svg
  public/svg/game-img.svg
  public/svg/mobile-img.svg
  public/svg/web-app.svg
  src/components/CallToAction/CallToAction.jsx
  src/components/FeaturesSection/FeaturesSection.jsx
  src/components/HeroSection/HeroSection.jsx
  src/components/HomeContent/HomeContent.jsx
  src/components/HomeContent/RecentJobs.jsx
  src/components/HomeContent/Testimonials.jsx
  src/components/ServiceCard/ServiceCard.jsx
  src/components/ServicesSection/ServicesSection.jsx
  src/components/TestimonialCard/TestimonialCard.jsx
  src/pages/ConfirmAccount.jsx
  src/pages/Explore.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/ResetPassword.jsx
  src/pages/SignUp.jsx
  src/redux/actions/services.js
  src/redux/actions/testimonials.js
  src/redux/reducers/services.js
  src/redux/reducers/testimonials.js
  src/redux/store.js
  src/utils/ServicesData.js
  src/utils/TestimonialsData.js
  yarn.lock
Labels: enhancement

#19 Fixed hero section extra padding issue
  src/components/HeroSection/HeroSection.jsx
Labels: awaiting-review, improvement, ui/ux

#18 Navbar fixed on top; Resolves #17;
  src/components/Header/Header.css
  src/components/Header/Header.jsx
Labels: awaiting-review, improvement, ui/ux

#22 bug fixed in explore page and home page
  src/components/ExploreContent/ExploreContent.jsx
  src/components/HomeContent/RecentJobs.jsx
Labels: bug, awaiting-review

#21 Added guest layout
  src/App.js
  src/layouts/GuestLayout.jsx
  src/pages/ConfirmAccount.jsx
  src/pages/Explore.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/ResetPassword.jsx
  src/pages/SignUp.jsx
Labels: enhancement, in-review, awaiting-review

#23 Fixes issue #10 : Mobile navbar
  src/components/Header/Header.jsx
  src/components/MobileDrawer/MobileDrawer.jsx
Labels: improvement

#25 Added border shadow for footer
  src/components/Footer/Footer.jsx
Labels: improvement

#24 404 page
  public/svg/page-not-found.svg
  src/layouts/GuestLayout.jsx
  src/pages/PageNotFound.jsx
Labels: enhancement, awaiting-review

#26 Proposal form
  src/components/ExploreContent/ExploreContent.jsx
  src/components/JobDetailsModal/JobDetailsModal.jsx
  src/components/ProposalForm/ProposalForm.jsx
  src/helpers/api/developer.js
  src/redux/actions/proposalData.js
  src/redux/reducers/proposalData.js
  src/redux/store.js
Labels: enhancement, awaiting-review, ui/ux
